### ISSUE TITLE
Administrator mode

### ISSUE THREAD

**Issue by Jaap-van-Hengstum** [ililim/dual-key-remap#1]
I discovered that when running Intellij in administrator mode, dual-key-remap only worked when also started in administrator mode.

Maybe something to mention in the documentation.

**Comment by ililim** [comment]
That's a good point, I should add that to the README. Same goes for working in other elevated windows, e.g. task manager.

I've been thinking on how to handle this better in the future, without needing to request elevation each time. Perhaps in a future release, I can register dual-key-remap as scheduled background task with a simple installer. That way it would run as an elevated background process on startup by default.

**Comment by Konfekt** [comment]
This can be circumvented by creating an "Elevated Shortcut", for example by [Winaero Tweaker](https://winaero.com/comment.php?comment.news.1836).

**Comment by badgh** [comment]
Is there any workaround so far to launch dual-key-remap in admin mode at startup? I tried making dual-key-remap.lnk file run as admin in startup folder, but it doesn't work.

**Comment by Konfekt** [comment]
Create an elevated shortcut by <https://winaero.com/comment.php?comment.news.1836> and put it into the startup folder `C:\Users\<user name>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`

**Comment by ililim** [comment]
This has been added to the README. In the future I'd like to add an (optional) installer that can set these kind of things up for you - but for now having the user do it manually should be OK. I imagine it's mostly technically savvy people using this tool.
