### ISSUE TITLE
Lack of During Pressed Functionality

### ISSUE THREAD

**Issue by Stolyassa** [ililim/dual-key-remap#10]
Is it possible to keep the remapped key pressed during the physical key is pressed?

For example; to use as an hotkey to push to talk in commutication programs. I really need it :)

**Comment by ililim** [comment]
Hmm, I'm not sure I understand the use-case, could you elaborate? The app is designed to support making a key into both a modifier and a tappable key (i.e. Ctrl+Escape). But if you need a key to be a modifier on hold and a modifier when pressed with other keys, isn't that the behavior of regular unmapped modifier key?

**Comment by Stolyassa** [comment]
> // Beginning of Tappable Key Explanation
> I need pysical CapsLock button position fuctions as my push to talk button in Teamspeak3 and Discord.
> For some reason (about other programs that I use), I can not assign CapsLock key itself as my push to talk button.
> 
> So, I remap CapsLock to ScrollLock and I use push to talk with ScrollLock.
> 
> But now unfortunately, when I keep the remapped key held down for long time, It does not take in consideration the time. The program only sends ScrollLock signal once when I released the key, so I can not talk with that key.
> // End of Tappable Key Explanation

The other story about modifier key is more compilated than this one.

> // Beginning of Modifier Key Explanation
> Obviously, I will need CapsLock functionality itself. I might use CapsLock itself as CapsLock with pressing together with e.g: CTRL specifically.  But, If the second key remains random as you arranged in the program that would prevent me do something else with the keyboard while talking in Discord. For my use-case, the second key has to be specified, not random.
> // End of Modifier Key Explanation

I know the upper is a very specific use-case. I found a work-around with using a bunch of other programs together, in order to do this use-case right now. But still, having trouble :)


> // Beginning of Unrelated another Use-case
> Also, that would be awesome, if I could use home-end buttons in the keyboard as forward-bacward buttons (4th-5th keys) in the mouse. 
> // End of Unrelated another Use-case

Couldn't find any tool doing the unrelated use-case without trouble in every application that I use.

**Comment by ililim** [comment]
Hmm, I think that for this specific use-case your best bet would be to write a simple https://www.autohotkey.com/ script.

**Comment by Stolyassa** [comment]
Autohotkey and every other similar programs are not working for all programs I use. They are not my options. There are only 2 programs called KeyExtender and KeyRemapper are working good for my use case. Unfortunately they are trial versions, they are not free or open source programs.

I would implement my use case into this project but It seems like I can't right now.
I knew C 5 years ago. Is this language you use C++? I hardly understand the code.

**Comment by ililim** [comment]
Have you tried running the AHK programs as administrator? That often solves a lot of compatibility issues. You could definitely fork this project and add this feature. It's all written in C.

**Comment by Stolyassa** [comment]
Yes. It isn't about AHK programs. It's about the programs that I use :) They block most AHKs.
