### ISSUE TITLE
Significant lag when using vim on wsl with the Hyper Terminal

### ISSUE THREAD

**Issue by jthn** [ililim/dual-key-remap#12]
When I am running vim8 or nvim on wsl and [hyper](https://hyper.is/), I am getting significant delay when using either as a modifier or as escape.  Roughly 3-5 seconds between keypress and it executing.  Interestingly enough, keypresses registers immediately when using just the hyper by itself, and escape works immediately when using vim8 on wsl on PowerShell.

Is there anything that I can do to help debug this?  Seems like a very unusual edge case that might be worth digging into.

**Comment by ililim** [comment]
Hmm, interesting edge case! There is a couple things you could do to help investigate this:
1) Add `debug=1` to your config.txt, which should log some messages to an open console window. Let me know if there is anything specific that happens there. (If everything runs correctly you will just see a log of every key pressed) (I assume you're running version 0.4?)
2) In the same conditions, try running a basic [autohotkey](https://github.com/Lexikos/AutoHotkey_L) script (without dual-key-remap running) (perhaps a simple script such as `Capslock::Esc` would do the trick). AHK uses the same API's for hooking into Windows – depending on the results we can narrow down the source of the delay.

**Comment by ililim** [comment]
@jthn Are you still running into this issue?

**Comment by ililim** [comment]
@jthn Please let me know if you're still running into this issue, otherwise I'll close it until someone else runs into this.
