### ISSUE TITLE
remap double shift to capslock

### ISSUE THREAD

**Issue by Badlapje** [ililim/dual-key-remap#13]
Is it possible to remap tapping shift twice to capslock?  I don't see a way to do so in the wiki, but maybe i'm missing someting.

If not, can this be added?

**Comment by ililim** [comment]
The purpose of this application is pretty focused: To create a dual role modifier keys, so unfortunately this use case is outside of our scope.

That said, something like what you are looking for can be accomplished with [AutoHotkey](https://www.autohotkey.com/).
