### ISSUE TITLE
Punctuation Keys

### ISSUE THREAD

**Issue by juanolon** [ililim/dual-key-remap#14]
Hello,
I'm trying to map the left shift when pressed alone with "("

```
remap_key=LEFT_SHIFT
when_alone=(
with_other=LEFT_SHIFT

remap_key=RIGHT_SHIFT
when_alone=)
with_other=RIGHT_SHIFT
```

but when pressed it, i get a "9". It also happen with any punctuation character. It seems not possible to map any punctuation character because on the key table they have the same value with them correspondend number eg. "9" and "(" have the same value.

https://github.com/ililim/dual-key-remap/blob/master/dual-key-remap.c#L149

How was this mean to work?

Thanks!

**Comment by ililim** [comment]
You're totally right - this should definitely be fixed.

**Comment by l13rb4git** [comment]
Any progress on that issue?

**Comment by ililim** [comment]
I'm going to have to remove those mappings - they don't fit how the app works. For now dual key remap can't output text ; it's intended as a modifier remapping tool primarily.

**Comment by ililim** [comment]
Should be fixed in https://github.com/ililim/dual-key-remap/discussions/36 If not, please feel free to open a new issue :)
