### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by VictorYing** [ililim/dual-key-remap#15]
Thanks for developing this nice little utility! Could you please add a LICENSE or COPYING file to clarify what permissions you'd like to give us users to use, share, or modify this? GitHub makes it easy for you to do that by going to https://github.com/ililim/dual-key-remap/community/license/new

Here is a website created by GitHub that might provide helpful information and suggestions: https://choosealicense.com/

**Comment by ililim** [comment]
Good call, I'll review my options and will add a LICENSE.

**Comment by ililim** [comment]
Added in 0096fab316ab3aad8754b11eebacf35ff019b190.
