### ISSUE TITLE
Not working with Firefox

### ISSUE THREAD

**Issue by Babbie** [ililim/dual-key-remap#16]
Like the title said, running this program in default configuration works perfectly fine, except in Firefox, where CapsLock only ever sends an Escape, not Ctrl + whatever key you press. This includes both the browser itself and any webpages you visit.

**Comment by ililim** [comment]
I was unable to reproduce this issue (Windows 10 1903, Firefox 70). The remapping seems to work the same just like in any other application. Is there a chance that either a browser extension or other application is interfering with the remapping?

**Comment by Babbie** [comment]
I'm now noticing that for a short while (a couple of minutes) after booting, the mapping works fine in Firefox, but after a while, unfocusing and refocusing Firefox will cause it to not work properly. Is there some sort of tooling or debugging I can use to provide more info? I'm on the same versions as you.

**Comment by ililim** [comment]
Yes there is: in your `config.txt` you can add the line `debug=1` and then relaunch the application. The console window should stay visible and give you some output.

Let me know what you see, this is certainly odd behaviour – especially if it works for a bit and then stops working. Do you have any other software that affects the keyboard?

**Comment by Babbie** [comment]
Pressing CAPS + T in any window gives me the following:
```
Logged keypress (Injected: 0, vkCode: 20, scanCode: 58, flags: 0, dwExtraInfo: 0
Logged keypress (Injected: 0, vkCode: 84, scanCode: 20, flags: 0, dwExtraInfo: 0
Logged keypress (Injected: 1, vkCode: 162, scanCode: 29, flags: 16, dwExtraInfo: 4291022551
Logged keypress (Injected: 0, vkCode: 84, scanCode: 20, flags: 128, dwExtraInfo: 0
Logged keypress (Injected: 0, vkCode: 20, scanCode: 58, flags: 128, dwExtraInfo: 0
Logged keypress (Injected: 1, vkCode: 162, scanCode: 29, flags: 144, dwExtraInfo: 4291022551
```
In Firefox, it gives me this:
```
Logged keypress (Injected: 0, vkCode: 20, scanCode: 58, flags: 0, dwExtraInfo: 0
Logged keypress (Injected: 0, vkCode: 20, scanCode: 58, flags: 128, dwExtraInfo: 0
Logged keypress (Injected: 1, vkCode: 27, scanCode: 1, flags: 16, dwExtraInfo: 4291022551
Logged keypress (Injected: 1, vkCode: 27, scanCode: 1, flags: 144, dwExtraInfo: 4291022551
```
As far as I'm aware, I'm not running anything that should influence the keyboard, and at the very least not CTRL + T or CAPS + T.

**Comment by ililim** [comment]
Hmm, I was unable to reproduce the above on a few machines and VMs. I'll have to to think on how I can capture some more debug information in the next build to investigate this further.

**Comment by juan-db** [comment]
@Babbie have you tried incognito/private browsing to see if maybe a plugin is affecting it?

**Comment by Babbie** [comment]
Yes, I've also manually disabled all browser plugins and restarted, to no avail.

**Comment by ililim** [comment]
Could not reproduce. Don't think this issue can be actioned at this time (please feel free to re-open if you have a suggestion to debug this).
