### ISSUE TITLE
Disable per application?

### ISSUE THREAD

**Issue by mg979** [ililim/dual-key-remap#17]
Thanks for this program. Is there a way (or can it be added) a way to disable it inside certain windows/programs? In VirtualBox for example.

**Comment by ililim** [comment]
That's an interesting idea! I'd like to keep the purpose of the application focused, so most likely I wouldn't add this unless a lot of users were to request it.

There is a way to achieve this using additional tools that supports per application remapping (i.e. [AHK](https://github.com/Lexikos/AutoHotkey_L)):
* In DualKeyRemap map some rare key (i.e. F20) to Ctrl/Escape
* In the external tool enable/disable the mapping of CapsLock to F20 per application/window

**Comment by mg979** [comment]
Thanks for the answer. I'd prefer to avoid workarounds such as those, I was unhappy with the AHK solution because it was hacky and unpredictable, so that would be more of the same. I'll be content with what's possible now. Feel free to close this if it's not in the plans for now.
