### ISSUE TITLE
Ctrl + mouse wheel doesn't work

### ISSUE THREAD

**Issue by jeremies** [ililim/dual-key-remap#18]
I have remapped CapsLock to Escape when pressed alone and Ctrl when pressed with other keys. But if I use Ctrl + mouse wheel to increase zoom in some programs for example, it doesn't work in Windows 10.

**Comment by ililim** [comment]
Good point, I handled the mouse events but did not consider the mouse wheel use-case. I can look into adding it.

**Comment by ililim** [comment]
Fixed in v0.5. Latest release available [here](https://github.com/ililim/dual-key-remap/releases).
