### ISSUE TITLE
Remember to add execution permission on binary

### ISSUE THREAD

**Issue by federicosacerdoti** [ililim/dual-key-remap#19]
Excellent program, works without admin access on Window. One reminder, after unzipping (on Cygwin shell) I needed to add exe bits before running.

`chmod u+x dual-key-remap.exe`

Perhaps add something to docs. Thanks again!

**Comment by ililim** [comment]
Thanks!

Is this requirements that Cygwin specific? I seem to be able to run the command OK from the command prompt.

**Comment by federicosacerdoti** [comment]
Might be, I saw this on MobaXterm

Best,
FDS

**Comment by ililim** [comment]
I think this seems like this would be standard for any downloadable binary? (other exe's also run into this requirement I believe?)

Please feel free to re-open if something needs to adjusted as part of this project.
