### ISSUE TITLE
Ctrl + Mouse Click

### ISSUE THREAD

**Issue by JeffOwOSun** [ililim/dual-key-remap#2]
Currently mouse click doesn't result in CapsLock sending Ctrl. Is it difficult to implement?

**Comment by ililim** [comment]
Ah yes, that's correct, it would indeed make more sense to treat click+capslock as ctrl+click. This shouldn't be too difficult, I'll implement this with the next release.

**Comment by ililim** [comment]
This has been implemented in the [latest release (v0.4)](https://github.com/ililim/dual-key-remap/releases). Clicking (`MOUSE_DOWN`) will now trigger the dual key to send the `with_other` key (`CTRL` by default).
