### ISSUE TITLE
Remap exact accord

### ISSUE THREAD

**Issue by SynCap** [ililim/dual-key-remap#21]
How to remap exact accord <left_shift>+<right_shift> ==> <caps_lock>?

Well, <Caps_Lock> is now smart and useful but CapsLock mode is unreachable although useful in some cases.

For example VERY_LONG_NAME_OF_CONSTANT_NEED_TO_BE_ENTERED_IN_COMMAND_LINE.
In IDE it's easy to convert to uppercase but using such constants in CLI needs the extra manipulations.

Also, there are a lot of tasks with notebooks Fn key combinations that need to be remapped.

**Comment by ililim** [comment]
For general purpose remapping I recommend using [AutoHotkey](https://github.com/Lexikos/AutoHotkey_L). DualKeyRemap is meant to create the double modifier key as in  ["The Modern Space Cadet"](https://stevelosh.com/blog/2012/10/a-modern-space-cadet/#s13-control-escape), which AutoHotkey cannot do achieve without concessions.

Both tools can be used side-by-side.
