### ISSUE TITLE
[Question] How to map SHIFT+CAPS to actual CAPS LOCK?

### ISSUE THREAD

**Issue by zeroxia** [ililim/dual-key-remap#24]
Hello,

This tool is neat.
Sorry to raise an "issue" here, actually it's not an issue.

Just curious anybody has some elegant way to map "SHIFT+CAPS" to the original CAPS LOCK key behavior? So we can still have this funciton if sometimes it's necessary?

It looks that AutoHotKey can do it, but just asking if there is a better way, instead of running another background program.

**Comment by ililim** [comment]
Yeah, I would advice to use AutHotkey for this functionality. I run both dual-key-remap and AutHotkey alongside each-other.
