### ISSUE TITLE
Fails to work correctly in remote desktop connection

### ISSUE THREAD

**Issue by thelimberlambda** [ililim/dual-key-remap#26]
Version of `dual-key-remap`: 0.4

I am using the built-in Windows remote desktop client (`mstsc.exe`).

Also, I have the following configuration:

```
remap_key=CTRL
when_alone=ESCAPE
with_other=CTRL
```

I am using SharpKeys to swap Left Control with CapsLock.

When RDP'ing to a Windows host, although the "when alone" setting works in the remote host (that is, pressing CapsLock without anything else results in an Escape), holding down CapsLock (Control) and pressing another key results in the fact that Control is "down" being ignored—effectively this is as if I had typed the key without holding down Control.

Other things I've tried, without success:

- Taking SharpKeys out of the picture by disabling it, and using a second "remap/alone/other" setting in config.txt to swap CapsLock and Control;
- Using the virtual key codes mentioned in the dual-key-remap documentation (with all three permutations of `remap_key` and `with_other`).

**Comment by ililim** [comment]
Was this resolved?

**Comment by thelimberlambda** [comment]
No, it hasn't, although turning debugging on has shown that only _some_ keys result in the hook function being called when `mstsc.exe` has focus (or ... at least, result in the debug `printf` being called)—in particular, pressing normal keys (like letters) don't yield a corresponding `printf` line.

**Comment by Muzzamil1** [comment]
Any update?

**Comment by thelimberlambda** [comment]
@Muzzamil1 I submitted a pull request some time ago.  @ililim ; any progress? https://github.com/ililim/dual-key-remap/pull/27#issue-481305136

**Comment by Muzzamil1** [comment]
Thanks @thelimberlambda. I will ty it out.

**Comment by ililim** [comment]
Should be fixed in https://github.com/ililim/dual-key-remap/discussions/36 If not, please feel free to open a new issue :)
