### ISSUE TITLE
Certain combos not working

### ISSUE THREAD

**Issue by account-sxf** [ililim/dual-key-remap#28]
Ctrl+Shift+X is not working in VS Code, and I assume elsewhere.

Ctrl+Alt+Del is also not working.

**Comment by account-sxf** [comment]
I believe the reason for this is highlighted in the readme provided with the current version:
> ### Shortcuts that require Escape
> 
> Certain applications might require shortcuts such as Shift+Escape. These can still be launched with Dual Key Remap. To launch these, simply hold the modifier keys (e.g. Shift, Ctrl) first and press the CapsLock key last. Dual Key Remap will send the Shift+Escape key combination as expected!
> 
> The reason this works is because Dual Key Remap sends Escape or Ctrl depending on whether any other keys where pressed _after_ CapsLock was held down, so tapping CapsLock as the last part of a sequence of keys will always send Escape.

**Comment by account-sxf** [comment]
Strangely other Ctrl+Shift combos are working in VS Codium, such as Ctrl+Shift+E to bring up the explorer.

**Comment by Radivarig** [comment]
Also pressing anything before the Ctrl doesn't work, `Shift + Ctrl + something` ignores `Ctrl`, but `Ctrl + Shift + something` works.

**Comment by ililim** [comment]
I'll take a look at this issue!

**Comment by ililim** [comment]
Should be fixed in https://github.com/ililim/dual-key-remap/discussions/36 If not, please feel free to open a new issue :)
