### ISSUE TITLE
Find program which currently occupies a key combination? Re-assignment from other computer?

### ISSUE THREAD

**Issue by pstein** [ililim/dual-key-remap#31]
In former times my PaintShopPro software assigned a certain function to <Alt>+H

Then, after some month, this <ALT>+H assignment does not work any more (other key combinations from PSP still work).
I don't know which new program destroyed (accidentially) the link between >ALT>+H and the PSP function.

How can I find it out?

Is there a way to detect which program occupies currently <ALT>+H now?

Assume I have a second computer with the same PaintShopPro software. <Alt>+H works there.
Can I somehow extract the key assignment from Registry over there, then copy it to my notebook and insert it into Registry?

Peter

**Comment by ililim** [comment]
Sorry, this is out of scope for this program.
