### ISSUE TITLE
Question: is there a way to increase the "with_other" delay time

### ISSUE THREAD

**Issue by sondredl** [ililim/dual-key-remap#38]
I remapped space to be shift when held, however it sometimes activates the "when_held" slightly to quickly changing spaces in my text for capital letters.

**Comment by ililim** [comment]
Hmm could you elaborate with more detail? Do you mean that your fingers move too fast and the key isn't fully depressed?

If so, I'm not sure what can be done here, it's very hard to tell apart the natural roll-over of typing vs someone executing a two key shortcut very quickly (e.g. CTRL+C).
