### ISSUE TITLE
Remapping the with_other key with AHK

### ISSUE THREAD

**Issue by flimofly** [ililim/dual-key-remap#41]
I run into trouble trying to implement a basic one-on-one AHK remap of the `with_other` key.  

I have this in my config file:
```
remap_key=CAPSLOCK
when_alone=ESCAPE
with_other=LEFT_CTRL
```

with this in AHK:
```
LCtrl::RAlt
```
**Expected behavior:** 
I am trying to use my CapsLock key as Esc/Ctrl, and my left Ctrl key as right Alt on a US-style keyboard, which does not have AltGr but does have a right Alt key and a right Ctrl key.

**Actual behavior:** 
- CapsLock works as Esc but not as Left_Ctrl

**Comment by ililim** [comment]
I tried this and seems to me to work as expected:

- DualKeyRemap remaps CapsLock -> LeftCtrl
- Then AHK remaps LeftCtrl -> LeftAlt

If you don't want the two apps to conflict you could do the following:
- Remap CapsLock -> **Right**Ctrl in Dual Key Remap
- Remap LeftCtrl -> LeftAlt in AHK
