### ISSUE TITLE
question

### ISSUE THREAD

**Issue by salembaba** [ililim/dual-key-remap#42]
Dear ililim
I need to change CAPSLOCK key to type Unicode Character “پ” (U+067E) with      UTF-8 Encoding:	0xD9 0xBE in arabic set
what shall I write in config.txt?

**Comment by ililim** [comment]
Hi there, for general key remapping I recommend using AutoHotkey instead. This tool is specialized for the "Dual Key" modifier use-case.

**Comment by salembaba** [comment]
I prefer the Dual key remap because it does not need admin password but AutoHotKey needs it.

**Comment by ililim** [comment]
You could write the AHK script on a different machine and [compile it to a standalone exe file](https://www.autohotkey.com/docs/Scripts.htm#ahk2exe). Then that exe file should work without installation - just like dual-key-remap.

**Comment by salembaba** [comment]
Perfect, Thank you very much.
