### ISSUE TITLE
Program window does not go to background  on windows 11

### ISSUE THREAD

**Issue by ascii78** [ililim/dual-key-remap#43]
Just noticed that on windows 11 the program window stays in the foreground, see image. Clicked on the 0.6 version, so probably the version string is old as well ? Rest of the program works fine.

![Screenshot 2022-02-28 150556](https://user-images.githubusercontent.com/1138654/155997259-e1d8f10e-0876-4744-984c-5725f5e9c113.png)
.

**Comment by ililim** [comment]
Ah interesting. I don't have w11 myself so can't test, but I'll do some reading as to why this might be. If anyone has any ideas it would be much appreciated.

**Comment by ililim** [comment]
@ascii78 can you confirm that you don't have `debug=1` set in your config?

**Comment by ascii78** [comment]
Hi,

So, I won't have access anymore to the windows 11 install, so this is just from memory. I did not configure anything and just used the stock config.txt from the zipfile, so that would be without debug=1.

**Comment by directspeed** [comment]
I am facing same issue

**Comment by directspeed** [comment]
> Just noticed that on windows 11 the program window stays in the foreground, see image. Clicked on the 0.6 version, so probably the version string is old as well ? Rest of the program works fine.
> 
> ![Screenshot 2022-02-28 150556](https://user-images.githubusercontent.com/1138654/155997259-e1d8f10e-0876-4744-984c-5725f5e9c113.png) .

I am facing same issue in windows 11

**Comment by ililim** [comment]
Thanks @mrgauravcs that helped. Looks like this is due to the new terminal application not show/hiding the same way as the old terminal app:
https://github.com/microsoft/terminal/issues/12570

Seems like there are other ways I can show/hide the window, I'll take a look at those.

**Comment by bsiegel** [comment]
Also ran into this, it seems like the stance of the Windows Terminal developers is that applications should not launch a window and then attempt to hide it - see https://github.com/microsoft/terminal/issues/11627#issuecomment-953164498. The trick no longer works because Windows Terminal doesn't have a 1:1 mapping of processes to windows.

The recommended approach seems to be to build the application targeting the Windows GUI subsystem (`/SUBSYSTEM:WINDOWS`) rather than the Console subsystem.

**Comment by ililim** [comment]
Nice summary @bsiegel! I'll give this a shot and will distribute a new build if I can get it work :)

**Comment by bsiegel** [comment]
Sorry for the delay - tested here and confirmed this seems to fix the issue. When Windows Terminal is the default console host application, v0.6 would cause a new WT window to appear upon launch. v0.7 does not cause a new window to appear. Also verified that when `debug=1` is added to the config file, the app does create its own terminal window and that the logging output works as expected.

Also just useful to note, this is not just a Win11 issue - any user who has installed Windows Terminal and selected to use Windows Terminal as the default console host application from within its Settings will experience the issue. Win11 is just the first version of Windows to come with WT installed by default.

**Comment by ililim** [comment]
Great to hear! I published the 0.7 release. Thanks for you help @bsiegel!
