### ISSUE TITLE
Not working in Parsec

### ISSUE THREAD

**Issue by eidetic-av** [ililim/dual-key-remap#48]
This application works fine in all other applications that I use, but when using [Parsec](https://parsec.app/), remappings are not considered and the keyboard behaves like default. 

When the Parsec window is focused, the dual-key-remap debug window (when setting debug=1 in config) does not log any input events at all. 

Perhaps it's related to #40, although this issue occurs even when no remote session is established, and only the Parsec settings window is focused.

Is there some common reason that some applications work while others do not? Or is it more something to figure out case-by-case.

Cheers.

**Comment by ililim** [comment]
I'm guessing that it would take some special handling to handle remote desktop software. 
Our of curiosity, have you tried AutoHotkey? Does it work with Parsec or not? If AHK doesn't work then I'm not sure there is much I can do, but if it does, I can see if I can recreate their fix around this.

**Comment by eidetic-av** [comment]
Ah, I just tried AutoHotKey and it also does not work with Parsec.
No worries though, I'll just close this issue.
