### ISSUE TITLE
dual-key-remap v0.7 shown as Virus

### ISSUE THREAD

**Issue by codeRSH** [ililim/dual-key-remap#54]
Hi, 

I have been using your 0.5 version for sometime now. Now I wanted to start using 0.7 version due to Terminal not auto closing the window while running dual-key-remap. 

However, while downloading I am getting multiple warnings that zip downloaded contains 'virus'! Please see attached screenshot. 
![Virus 1](https://user-images.githubusercontent.com/4953198/192844300-660e7295-4419-4978-b407-ea831b8dc943.png)
![Virus 2](https://user-images.githubusercontent.com/4953198/192844322-d2750736-e012-49d1-8381-16f941b54139.png)

Any idea why this is happening and how this can be avoided?

**Comment by ililim** [comment]
Ah yes, 3rd party virus scanners are not reliable sadly. I would recommend sticking to windows defender.

I'm working on v0.8, which for some reason seems to not trigger alarms on virus total. I can release a new build next week!

**Comment by ililim** [comment]
I recompiled the v0.7 build with the latest Visual Studio toolkit, that seems to have appeased some of the virus scanners.
