### ISSUE TITLE
Usage with Japanese input

### ISSUE THREAD

**Issue by arthniwa** [ililim/dual-key-remap#55]
Thank you for this awesome script.

When I use the script with Japanese input (the default Microsoft IME), after pressing caps lock, it will behave like ctrl is always being pressed. For example, after I press ctrl+t to open a new tab in Chrome, if I scroll the mouse wheel the page will be zoomed. Only after I press a true ctrl key do things back to normal.

The problem seems to stem from the fact that in Japanese input method caps lock has some specific functions. For example, ctrl+caps lock will switch the input method to hiragana input.

**Comment by niwazuki** [comment]
OK, I got it working by first changing the registry as in [here](https://superuser.com/questions/949385/map-capslock-to-control-in-windows-10) and then treating caps lock as ctrl in the script. Would be good to be able to do it entirely through the script though.
