### ISSUE TITLE
Can not parse SCROLLLOCK as 'when_alone' and 'with_other' attributes

### ISSUE THREAD

**Issue by Stolyassa** [ililim/dual-key-remap#9]
Hello,

I can not understand why this config.txt not working?

`remap_key=CAPSLOCK`
`when_alone=SCROLLLOCK`
`with_other=SCROLLLOCK`

When I execute the ''dual-key-remap.exe" I get the following error in Command Line Window.

`Cannot parse line 3 in config: 'when_alone=SCROLLLOCK'. Make sure you've used the correct keycode, and that that there is no extraneous whitespace.`

**Comment by Stolyassa** [comment]
Solution is:

remap_key=CAPSLOCK
when_alone=ScrollLock
with_other=ScrollLock

But now, It is not working within some programs (Discord, TeamSpeak3, Games)

**Comment by Stolyassa** [comment]
Solution to prior problem is to run as administrator.

**Comment by ililim** [comment]
Ah, that's a bug actually. Indeed currently some key codes are not setup with the correct capitalization. I will fix this with the next release.

**Comment by ililim** [comment]
This has been fixed in the [latest release (v0.4)](https://github.com/ililim/dual-key-remap/releases). If you update from v0.3, you'll have to change `ScrollLock` to `SCROLLLOCK` in your config.
